name : Hprofile Action
# how this pipline will run workflow_dispatch means only run when we run manually can change it to push or anything
on : workflow_dispatch  
jobs : 
  Testing :
  #which runner
    runs-on : ubuntu-latest
    steps :
      - name : Code checkout
        uses: actions/checkout@v4

      - name : MavenTest
        run : mvn test

      #check style analysis
      - name : checkstyle
        run : mvn checkstyle:checkstyle

      - name : set java 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

      # Run sonar-scanner
      #jacoco.exec this is created when run mvn test
      #checkstyle-result.xml is used for checkout result
      - name: SonarQube Scan
        run: sonar-scanner
           -Dsonar.host.url=${{ secrets.SONAR_URL }}
           -Dsonar.login=${{ secrets.SONAR_TOCKEN }}
           -Dsonar.organization=${{ secrets.SONAR_ORG }}
           -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
           -Dsonar.sources=src/
           -Dsonar.junit.reportsPath=target/surefire-reports/ 
           -Dsonar.jacoco.reportsPath=target/jacoco.exec 
           -Dsonar.java.checkstyle.reportPaths=target/checkstyle-result.xml
           -Dsonar.java.binaries=target/test-classes/com/visualpathit/account/controllerTest/
  