name : Hprofile Action
# how this pipline will run workflow_dispatch means only run when we run manually can change it to push or anything
on : workflow_dispatch  
jobs : 
  Testing :
  #which runner
    runs-on : ubuntu-latest
    steps :
      - name : Code checkout
        uses: actions/checkout@v4

      - name : MavenTest
        run : mvn test

      #check style analysis
      - name : checkstyle
        run : mvn checkstyle:checkstyle
        